# Generated by Django 4.1 on 2022-08-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('fr', 'fr')], max_length=10),
        ),
    ]
